version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform

  build:
    commands:
      - echo Running Terraform Init
      - terraform init -input=false
      - echo Running Terraform Apply
      - terraform apply -input=false tfplan

  post_build:
    commands:
      - echo "Completed Terraform apply phase"

artifacts:
  files:
    - '**/*'

